version: "3.7"

services:
  app:
    image: node:12-alpine
    command: sh -c "yarn install && npm start"
    ports:
      - 3000:3000
    working_dir: /fearless-app
    volumes:
      - ./:/fearless-app
